import { MarkingScheme } from './types';

export const MARKING_SCHEMES: MarkingScheme[] = [
  // Odisha Exams
  {
    id: 'osssc-ri',
    name: 'OSSSC RI',
    positiveMarks: 1,
    negativeMarks: 0.33,
    description: 'Odisha Sub-Ordinate Staff Selection Commission - Revenue Inspector',
  },
  {
    id: 'ossc-cgl',
    name: 'OSSC CGL',
    positiveMarks: 1,
    negativeMarks: 0.25,
    description: 'Odisha Staff Selection Commission - Combined Graduate Level',
  },
  {
    id: 'ossc-junior-assistant',
    name: 'OSSC Junior Assistant',
    positiveMarks: 1,
    negativeMarks: 0.25,
    description: 'Odisha Staff Selection Commission - Junior Assistant',
  },
  {
    id: 'opsc-aso',
    name: 'OPSC ASO',
    positiveMarks: 1,
    negativeMarks: 0.25,
    description: 'Odisha Public Service Commission - Assistant Section Officer',
  },
  // SSC Exams
  {
    id: 'ssc-cgl',
    name: 'SSC CGL',
    positiveMarks: 2,
    negativeMarks: 0.5,
    description: 'Staff Selection Commission - Combined Graduate Level',
  },
  {
    id: 'ssc-chsl',
    name: 'SSC CHSL',
    positiveMarks: 2,
    negativeMarks: 0.5,
    description: 'Staff Selection Commission - Combined Higher Secondary Level',
  },
  {
    id: 'ssc-mts',
    name: 'SSC MTS',
    positiveMarks: 1,
    negativeMarks: 0.25,
    description: 'Staff Selection Commission - Multi Tasking Staff',
  },
  {
    id: 'ssc-gd',
    name: 'SSC GD',
    positiveMarks: 1,
    negativeMarks: 0.25,
    description: 'Staff Selection Commission - General Duty Constable',
  },
  // UPSC Exams
  {
    id: 'upsc-prelims',
    name: 'UPSC Prelims',
    positiveMarks: 2,
    negativeMarks: 0.67,
    description: 'Union Public Service Commission - Preliminary Examination',
  },
  // Banking Exams
  {
    id: 'ibps-po',
    name: 'IBPS PO',
    positiveMarks: 1,
    negativeMarks: 0.25,
    description: 'Institute of Banking Personnel Selection - Probationary Officer',
  },
  {
    id: 'ibps-clerk',
    name: 'IBPS Clerk',
    positiveMarks: 1,
    negativeMarks: 0.25,
    description: 'Institute of Banking Personnel Selection - Clerk',
  },
  {
    id: 'sbi-po',
    name: 'SBI PO',
    positiveMarks: 1,
    negativeMarks: 0.25,
    description: 'State Bank of India - Probationary Officer',
  },
  {
    id: 'sbi-clerk',
    name: 'SBI Clerk',
    positiveMarks: 1,
    negativeMarks: 0.25,
    description: 'State Bank of India - Clerk',
  },
  {
    id: 'rbi-assistant',
    name: 'RBI Assistant',
    positiveMarks: 1,
    negativeMarks: 0.25,
    description: 'Reserve Bank of India - Assistant',
  },
  // Railway Exams
  {
    id: 'rrb-ntpc',
    name: 'RRB NTPC',
    positiveMarks: 1,
    negativeMarks: 0.33,
    description: 'Railway Recruitment Board - Non-Technical Popular Categories',
  },
  {
    id: 'rrb-group-d',
    name: 'RRB Group D',
    positiveMarks: 1,
    negativeMarks: 0.33,
    description: 'Railway Recruitment Board - Group D',
  },
  {
    id: 'rrb-je',
    name: 'RRB JE',
    positiveMarks: 1,
    negativeMarks: 0.33,
    description: 'Railway Recruitment Board - Junior Engineer',
  },
  // Teaching Exams
  {
    id: 'ugc-net',
    name: 'UGC NET',
    positiveMarks: 2,
    negativeMarks: 0,
    description: 'National Eligibility Test - No Negative Marking',
  },
  {
    id: 'ctet',
    name: 'CTET',
    positiveMarks: 1,
    negativeMarks: 0,
    description: 'Central Teacher Eligibility Test - No Negative Marking',
  },
  {
    id: 'otet',
    name: 'OTET',
    positiveMarks: 1,
    negativeMarks: 0,
    description: 'Odisha Teacher Eligibility Test - No Negative Marking',
  },
  // Engineering Exams
  {
    id: 'gate',
    name: 'GATE',
    positiveMarks: 1,
    negativeMarks: 0.33,
    description: 'Graduate Aptitude Test in Engineering',
  },
  {
    id: 'jee-main',
    name: 'JEE Main',
    positiveMarks: 4,
    negativeMarks: 1,
    description: 'Joint Entrance Examination - Main',
  },
  {
    id: 'neet',
    name: 'NEET',
    positiveMarks: 4,
    negativeMarks: 1,
    description: 'National Eligibility cum Entrance Test',
  },
  // Management Exams
  {
    id: 'cat',
    name: 'CAT',
    positiveMarks: 3,
    negativeMarks: 1,
    description: 'Common Admission Test',
  },
  {
    id: 'mat',
    name: 'MAT',
    positiveMarks: 1,
    negativeMarks: 0.25,
    description: 'Management Aptitude Test',
  },
  {
    id: 'xat',
    name: 'XAT',
    positiveMarks: 1,
    negativeMarks: 0.25,
    description: 'Xavier Aptitude Test',
  },
  // Insurance Exams
  {
    id: 'lic-aao',
    name: 'LIC AAO',
    positiveMarks: 1,
    negativeMarks: 0.25,
    description: 'Life Insurance Corporation - Assistant Administrative Officer',
  },
  {
    id: 'lic-assistant',
    name: 'LIC Assistant',
    positiveMarks: 1,
    negativeMarks: 0.25,
    description: 'Life Insurance Corporation - Assistant',
  },
  // Defense Exams
  {
    id: 'nda',
    name: 'NDA',
    positiveMarks: 2.5,
    negativeMarks: 0.83,
    description: 'National Defence Academy - Mathematics & GAT',
  },
  {
    id: 'cds',
    name: 'CDS',
    positiveMarks: 1,
    negativeMarks: 0.33,
    description: 'Combined Defence Services',
  },
  {
    id: 'afcat',
    name: 'AFCAT',
    positiveMarks: 3,
    negativeMarks: 1,
    description: 'Air Force Common Admission Test',
  },
  // Custom
  {
    id: 'custom',
    name: 'Custom',
    positiveMarks: 1,
    negativeMarks: 0,
    description: 'Custom marking scheme - Set your own values',
  },
];

export const TOPICS = {
  MATH: [
    'Simple Interest',
    'Compound Interest',
    'Profit & Loss',
    'Discount',
    'Time & Work',
    'Time & Distance',
    'Percentage',
    'Ratio & Proportion',
    'Average',
    'Number System',
    'Algebra',
    'Geometry',
    'Trigonometry',
    'Mensuration',
    'Data Interpretation',
  ],
  REASONING: [
    'Analogy',
    'Classification',
    'Series',
    'Coding-Decoding',
    'Blood Relations',
    'Direction Sense',
    'Syllogism',
    'Puzzles',
    'Seating Arrangement',
    'Statement & Conclusion',
    'Venn Diagrams',
  ],
  ENGLISH: [
    'Reading Comprehension',
    'Grammar',
    'Vocabulary',
    'Sentence Correction',
    'Synonyms/Antonyms',
    'Idioms & Phrases',
    'One Word Substitution',
    'Fill in the Blanks',
    'Para Jumbles',
  ],
  GK: [
    'History',
    'Geography',
    'Polity',
    'Economics',
    'Science',
    'Current Affairs',
    'Static GK',
    'Computer Awareness',
    'Banking Awareness',
  ],
  ODIA: [
    'Sandhi',
    'Samasa',
    'Grammar',
    'Literature',
    'Vocabulary',
    'Comprehension',
  ],
  COMPUTER: [
    'Basic Computer',
    'MS Office',
    'Internet',
    'Operating Systems',
    'Database',
    'Networking',
    'Programming',
    'Shortcuts',
  ],
};

export const EXAM_PLATFORMS = [
  { name: 'TCS iON', pattern: /tcsion\.com|ion\.tcs/i },
  { name: 'Digialm', pattern: /digialm\.com/i },
  { name: 'NTA', pattern: /nta\.ac\.in|nta/i },
  { name: 'SSC Online', pattern: /ssc\.(nic\.)?in|ssc online/i },
  { name: 'IBPS', pattern: /ibps\.in/i },
  { name: 'Other', pattern: /.*/ },
];

export const COLORS = {
  correct: '#22c55e',
  incorrect: '#ef4444',
  skipped: '#f59e0b',
  primary: '#6366f1',
  secondary: '#8b5cf6',
  accent: '#06b6d4',
};

export const CATEGORIES = ['General', 'OBC', 'SC', 'ST', 'EWS'];

export const STATES = [
  'Odisha',
  'Andhra Pradesh',
  'Bihar',
  'Delhi',
  'Gujarat',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Punjab',
  'Rajasthan',
  'Tamil Nadu',
  'Telangana',
  'Uttar Pradesh',
  'West Bengal',
  'Other',
];
